# Generated by Django 5.1.7 on 2026-02-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_editora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editora',
            name='descricao',
        ),
        migrations.AddField(
            model_name='editora',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editora',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
